export type CatalogType = "movie" | "series" | "all" | "anime";

export interface CatalogFallback {
  name: string;
  type: CatalogType;
}

export const CATALOG_FALLBACKS: Record<string, CatalogFallback> = {
  "mdblist.100279": { name: "[Collection] Monsterverse", type: "all" },
  "mdblist.100467": { name: "[Awards] Oscar Winners", type: "movie" },
  "mdblist.101881": { name: "[Collection] IMDb Top 250 Movies", type: "movie" },
  "mdblist.101882": { name: "[Collection] IMDb Top 250 Shows", type: "series" },
  "mdblist.102986": { name: "[Collection] Back to The Future", type: "movie" },
  "mdblist.105063": { name: "[Collection] Harry Potter", type: "movie" },
  "mdblist.105130": { name: "[Collection] DC Shows", type: "series" },
  "mdblist.106355": { name: "[Director] Martin Scorsese", type: "movie" },
  "mdblist.116037": { name: "[Genre] Animated Movies", type: "movie" },
  "mdblist.116038": { name: "[Genre] Animated Shows", type: "series" },
  "mdblist.11753": { name: "[Top Row] 30 Shows of the Week", type: "series" },
  "mdblist.11754": { name: "[Top Row] 30 Movies of the Week", type: "movie" },
  "mdblist.119708": { name: "[Director] Wes Anderson", type: "movie" },
  "mdblist.124146": { name: "[Genre] War Movies", type: "movie" },
  "mdblist.125120": { name: "[Collection] Indiana Jones", type: "movie" },
  "mdblist.125124": { name: "[Collection] Pirates of the Caribbean", type: "movie" },
  "mdblist.125146": { name: "[Collection] Jurassic Park", type: "movie" },
  "mdblist.125458": { name: "[Collection] Terminator Universe", type: "all" },
  "mdblist.126338": { name: "[Genre] Christmas Movies 2", type: "movie" },
  "mdblist.127954": { name: "[Service] Hulu Shows", type: "series" },
  "mdblist.127955": { name: "[Service] Hulu Movies", type: "movie" },
  "mdblist.128063": { name: "[Collection] Marvel Shows", type: "series" },
  "mdblist.128261": { name: "[Genre] Romance Movies", type: "movie" },
  "mdblist.130778": { name: "[Genre] KDrama Movies", type: "movie" },
  "mdblist.136107": { name: "[Genre] Österreichische Serien", type: "series" },
  "mdblist.136229": { name: "[Genre] Österreichischer Film", type: "movie" },
  "mdblist.136620": { name: "[Genre] Seasonal", type: "movie" },
  "mdblist.136678": { name: "[Actor] Mila Kunis Shows", type: "series" },
  "mdblist.136684": { name: "[Actor] Matthew McConaughey Shows", type: "series" },
  "mdblist.136686": { name: "[Actor] Channing Tatum Shows", type: "series" },
  "mdblist.136692": { name: "[Actor] Melissa McCarthy Shows", type: "series" },
  "mdblist.136695": { name: "[Actor] Michael „Bully“ Herbig Shows", type: "series" },
  "mdblist.136700": { name: "[Actor] Jack Black Shows", type: "series" },
  "mdblist.136706": { name: "[Actor] Katherine Heigl Shows", type: "series" },
  "mdblist.136709": { name: "[Actor] Emma Stone Shows", type: "series" },
  "mdblist.140566": { name: "[Awards] Oscars 2026 Nominations", type: "movie" },
  "mdblist.142241": { name: "[Actor] Zendaya Shows", type: "series" },
  "mdblist.142242": { name: "[Actor] Robin Williams Shows", type: "series" },
  "mdblist.142243": { name: "[Actor] Dwayne Johnson Shows", type: "series" },
  "mdblist.143358": { name: "[Actor] Julia Roberts Shows", type: "series" },
  "mdblist.143365": { name: "[Actor] Robert Downey Jr. Shows", type: "series" },
  "mdblist.143373": { name: "[Actor] Johnny Depp Shows", type: "series" },
  "mdblist.143374": { name: "[Actor] Tom Holland Shows", type: "series" },
  "mdblist.143629": { name: "[Director] Quentin Tarantino", type: "movie" },
  "mdblist.143630": { name: "[Director] Ridley Scott", type: "movie" },
  "mdblist.143631": { name: "[Director] Steven Spielberg", type: "movie" },
  "mdblist.143632": { name: "[Director] Christopher Nolan", type: "movie" },
  "mdblist.143633": { name: "[Director] James Cameron", type: "movie" },
  "mdblist.143634": { name: "[Director] John Carpenter", type: "movie" },
  "mdblist.143635": { name: "[Director] Denis Villeneuve", type: "movie" },
  "mdblist.143637": { name: "[Actor] Johnny Depp Movies", type: "movie" },
  "mdblist.143639": { name: "[Actor] Dwayne Johnson Movies", type: "movie" },
  "mdblist.143640": { name: "[Actor] Sandra Bullock Movies", type: "movie" },
  "mdblist.143641": { name: "[Actor] Jennifer Lawrance Movies", type: "movie" },
  "mdblist.143642": { name: "[Actor] Brad Pitt Movies", type: "movie" },
  "mdblist.143643": { name: "[Actor] Angelina Jolie Movies", type: "movie" },
  "mdblist.143644": { name: "[Actor] Samuel L. Jackson Movies", type: "movie" },
  "mdblist.143645": { name: "[Actor] Matt Damon Movies", type: "movie" },
  "mdblist.143646": { name: "[Actor] Jason Statham Movies", type: "movie" },
  "mdblist.143648": { name: "[Actor] Harrison Ford Movies", type: "movie" },
  "mdblist.143650": { name: "[Actor] Adam Sandler Movies", type: "movie" },
  "mdblist.143651": { name: "[Actor] Morgan Freeman Movies", type: "movie" },
  "mdblist.143652": { name: "[Actor] Nicolas Cage Movies", type: "movie" },
  "mdblist.143653": { name: "[Actor] Anne Hathaway Movies", type: "movie" },
  "mdblist.143654": { name: "[Actor] Jim Carrey Movies", type: "movie" },
  "mdblist.143656": { name: "[Actor] Channing Tatum Movies", type: "movie" },
  "mdblist.143657": { name: "[Actor] George Clooney Movies", type: "movie" },
  "mdblist.143658": { name: "[Actor] Bill Murray Movies", type: "movie" },
  "mdblist.143659": { name: "[Actor] Ben Stiller Movies", type: "movie" },
  "mdblist.143660": { name: "[Actor] Owen Wilson Movies", type: "movie" },
  "mdblist.143661": { name: "[Actor] Jonah Hill Movies", type: "movie" },
  "mdblist.143662": { name: "[Actor] Margot Robbie Movies", type: "movie" },
  "mdblist.143663": { name: "[Actor] Daniel Craig Movies", type: "movie" },
  "mdblist.143664": { name: "[Actor] Jennifer Aniston Movies", type: "movie" },
  "mdblist.143665": { name: "[Actor] Millie Bobby Brown Movies", type: "movie" },
  "mdblist.143666": { name: "[Actor] Mila Kunis Movies", type: "movie" },
  "mdblist.143667": { name: "[Actor] Reese Witherspoon Movies", type: "movie" },
  "mdblist.143668": { name: "[Actor] Matthew McConaughey Movies", type: "movie" },
  "mdblist.143669": { name: "[Actor] Steve Carell Movies", type: "movie" },
  "mdblist.143670": { name: "[Actor] Melissa McCarthy Movies", type: "movie" },
  "mdblist.143671": { name: "[Actor] Jack Black Movies", type: "movie" },
  "mdblist.143672": { name: "[Actor] Katherine Heigl Movies", type: "movie" },
  "mdblist.143673": { name: "[Actor] Florence Pugh Movies", type: "movie" },
  "mdblist.143675": { name: "[Actor] Lily Collins Movies", type: "movie" },
  "mdblist.143677": { name: "[Actor] Emma Stone Movies", type: "movie" },
  "mdblist.143678": { name: "[Actor] Sydney Sweeney Movies", type: "movie" },
  "mdblist.143680": { name: "[Actor] Michael \"Bully\" Herbig Movies", type: "movie" },
  "mdblist.143681": { name: "[Actor] Nicole Kidman Movies", type: "movie" },
  "mdblist.143682": { name: "[Actor] Robin Williams Movies", type: "movie" },
  "mdblist.143685": { name: "[Actor] Tom Holland Movies", type: "movie" },
  "mdblist.143686": { name: "[Actor] Zendaya Movies", type: "movie" },
  "mdblist.143687": { name: "[Actor] Leonardo DiCaprio Movies", type: "movie" },
  "mdblist.143688": { name: "[Actor] Jenna Ortega Movies", type: "movie" },
  "mdblist.143689": { name: "[Actor] Ryan Reynolds Movies", type: "movie" },
  "mdblist.143690": { name: "[Actor] Benedict Cumberbatch Movies", type: "movie" },
  "mdblist.143691": { name: "[Actor] Julia Roberts Movies", type: "movie" },
  "mdblist.143692": { name: "[Actor] Tom Cruise Movies", type: "movie" },
  "mdblist.143694": { name: "[Actor] Meryl Streep Movies", type: "movie" },
  "mdblist.143696": { name: "[Actor] Robert Downey Jr. Movies", type: "movie" },
  "mdblist.143704": { name: "[Actor] Nicole Kidman Shows", type: "series" },
  "mdblist.143705": { name: "[Actor] Jenna Ortega Shows", type: "series" },
  "mdblist.143706": { name: "[Actor] Harrison Ford Shows", type: "series" },
  "mdblist.143708": { name: "[Actor] Jennifer Aniston Shows", type: "series" },
  "mdblist.143709": { name: "[Actor] Reese Witherspoon Shows", type: "series" },
  "mdblist.143710": { name: "[Actor] Millie Bobby Brown Shows", type: "series" },
  "mdblist.143712": { name: "[Actor] Steve Carell Shows", type: "series" },
  "mdblist.143713": { name: "[Actor] Sydney Sweeney Shows", type: "series" },
  "mdblist.143714": { name: "[Actor] Lily Collins Shows", type: "series" },
  "mdblist.143715": { name: "[Actor] Nicolas Cage Shows", type: "series" },
  "mdblist.143716": { name: "[Actor] Florence Pugh Shows", type: "series" },
  "mdblist.143717": { name: "[Actor] Samuel L. Jackson Shows", type: "series" },
  "mdblist.143718": { name: "[Actor] Benedict Cumberbatch Shows", type: "series" },
  "mdblist.143720": { name: "[Actor] George Clooney Shows", type: "series" },
  "mdblist.143863": { name: "[Collection] Star Wars Universe", type: "all" },
  "mdblist.143865": { name: "[Collection] The Godfather", type: "movie" },
  "mdblist.143866": { name: "[Collection] Dune", type: "movie" },
  "mdblist.143867": { name: "[Collection] Avatar", type: "movie" },
  "mdblist.143868": { name: "[Collection] Hunger Games", type: "movie" },
  "mdblist.143870": { name: "[Collection] Star Trek Universe", type: "all" },
  "mdblist.143882": { name: "[Collection] John Wick Universe", type: "all" },
  "mdblist.143885": { name: "[Collection] Eberhofer Krimis", type: "movie" },
  "mdblist.145242": { name: "[Actor] Denzel Washington Movies", type: "movie" },
  "mdblist.146022": { name: "[Collection] Alien", type: "movie" },
  "mdblist.147855": { name: "[Actor] Timothée Chalamet Movies & Shows", type: "all" },
  "mdblist.149615": { name: "[Awards] Golden Globes Winners", type: "movie" },
  "mdblist.149616": { name: "[Awards] Cannes Palme d'Or", type: "movie" },
  "mdblist.149620": { name: "[Awards] Emmy Awards 2000-2025", type: "series" },
  "mdblist.149884": { name: "[Genre] Adventure Shows", type: "series" },
  "mdblist.149887": { name: "[Genre] War Shows", type: "series" },
  "mdblist.149898": { name: "[Genre] History Shows", type: "series" },
  "mdblist.149984": { name: "[Director] Spike Lee", type: "movie" },
  "mdblist.150299": { name: "[Genre] Musical Movies", type: "movie" },
  "mdblist.150391": { name: "[Director] David Lynch", type: "movie" },
  "mdblist.150631": { name: "[Collection] Scream", type: "all" },
  "mdblist.151293": { name: "[Director] Brian De Palma", type: "movie" },
  "mdblist.151294": { name: "[Actor] Christian Bale Movies", type: "movie" },
  "mdblist.151297": { name: "[Actor] Sylvester Stallone Movies & Shows", type: "all" },
  "mdblist.151298": { name: "[Actor] Jackie Chan Movies & Shows", type: "all" },
  "mdblist.151300": { name: "[Actor] Clint Eastwood Movies", type: "movie" },
  "mdblist.151301": { name: "[Actor] Arnold Schwarzenegger Movies & Shows", type: "all" },
  "mdblist.16826": { name: "[Collection] Rocky / Creed", type: "movie" },
  "mdblist.2195": { name: "[Genre] Comedy Movies", type: "movie" },
  "mdblist.16267": { name: "[Header] Movies for Header", type: "movie" },
  "mdblist.2407": { name: "[Genre] Action Movies", type: "movie" },
  "mdblist.2408": { name: "[Genre] Drama Movies", type: "movie" },
  "mdblist.2410": { name: "[Genre] Horror Movies", type: "movie" },
  "mdblist.2411": { name: "[Genre] Crime Movies", type: "movie" },
  "mdblist.2412": { name: "[Genre] Fantasy/Sci-Fi Movies", type: "movie" },
  "mdblist.2415": { name: "[Genre] Family Movies", type: "movie" },
  "mdblist.2416": { name: "[Genre] Mystery Movies", type: "movie" },
  "mdblist.2820": { name: "[Year] Popular 1970s Movies", type: "movie" },
  "mdblist.3022": { name: "[Collection] Marvel Movies", type: "movie" },
  "mdblist.3095": { name: "[Top] Disney+ Movies", type: "movie" },
  "mdblist.3126": { name: "[Genre] Crime Shows", type: "series" },
  "mdblist.31309": { name: "[Collection] Mission Impossible", type: "movie" },
  "mdblist.31324": { name: "[Collection] Rambo", type: "movie" },
  "mdblist.3892": { name: "[Genre] Mindfuck Movies", type: "movie" },
  "mdblist.43438": { name: "[Service] Shudder Shows", type: "series" },
  "mdblist.53976": { name: "[Director] Alfred Hitchcock", type: "movie" },
  "mdblist.5771": { name: "[Genre] Bollywood Movies", type: "movie" },
  "mdblist.59631": { name: "[Collection] Fast and Furious", type: "movie" },
  "mdblist.62454": { name: "[Service] Shudder Movies", type: "movie" },
  "mdblist.6605": { name: "[Genre] Family Shows", type: "series" },
  "mdblist.6614": { name: "[Genre] Mystery Shows", type: "series" },
  "mdblist.6617": { name: "[Genre] Romance Shows", type: "series" },
  "mdblist.6629": { name: "[Genre] Adventure Movies", type: "movie" },
  "mdblist.6638": { name: "[Genre] History Movies", type: "movie" },
  "mdblist.7444": { name: "[Top] Apple TV Shows", type: "series" },
  "mdblist.7577": { name: "[Genre] KDrama Shows", type: "series" },
  "mdblist.75976": { name: "[Director] Francis Ford Coppola", type: "movie" },
  "mdblist.75977": { name: "[Director] Paul Thomas Anderson", type: "movie" },
  "mdblist.75982": { name: "[Director] Guillermo del Toro", type: "movie" },
  "mdblist.7947": { name: "[Collection] James Bond", type: "movie" },
  "mdblist.8113": { name: "[Genre] Christmas Movies", type: "movie" },
  "mdblist.83484": { name: "[Service] Peacock Shows", type: "series" },
  "mdblist.83487": { name: "[Service] Peacock Movies", type: "movie" },
  "mdblist.84401": { name: "[Genre] Top Reality TV", type: "series" },
  "mdblist.84403": { name: "[Genre] Documentary Shows", type: "series" },
  "mdblist.84677": { name: "[Genre] Documentary Movies", type: "movie" },
  "mdblist.85399": { name: "[Director] Peter Jackson", type: "movie" },
  "mdblist.86625": { name: "[Service] Apple TV Shows", type: "series" },
  "mdblist.86710": { name: "[Discover] LatestShows", type: "series" },
  "mdblist.86751": { name: "[Service] Netflix Shows", type: "series" },
  "mdblist.86752": { name: "[Service] Netflix Movies", type: "movie" },
  "mdblist.86753": { name: "[Service] Amazon Prime Shows", type: "series" },
  "mdblist.86755": { name: "[Service] Amazon Prime Movies", type: "movie" },
  "mdblist.86757": { name: "[Service] Apple TV Movies", type: "movie" },
  "mdblist.86758": { name: "[Service] Disney+ Shows", type: "series" },
  "mdblist.86759": { name: "[Service] Disney+ Movies", type: "movie" },
  "mdblist.86761": { name: "[Service]  Paramount+ Shows", type: "series" },
  "mdblist.8682": { name: "[Collection] Transformers", type: "movie" },
  "mdblist.86934": { name: "[Discover] Latest Movies", type: "movie" },
  "mdblist.87667": { name: "[Top] Trakt's Trending Movies", type: "movie" },
  "mdblist.88302": { name: "[Discover] Trending Movies", type: "movie" },
  "mdblist.88303": { name: "[Discover] Trending Shows", type: "series" },
  "mdblist.88317": { name: "[Top] Apple TV Movies", type: "movie" },
  "mdblist.88323": { name: "[Top] Disney+ Shows", type: "series" },
  "mdblist.88324": { name: "[Top] HBO Max Movies", type: "movie" },
  "mdblist.88325": { name: "[Top] HBO Max Shows", type: "series" },
  "mdblist.88328": { name: "[Top] Netflix Movies", type: "movie" },
  "mdblist.88329": { name: "[Top] Netflix Shows", type: "series" },
  "mdblist.88330": { name: "[Service] Paramount+ Movies", type: "movie" },
  "mdblist.88331": { name: "[Top] Paramount+ Shows", type: "series" },
  "mdblist.88332": { name: "[Top] Prime Movies", type: "movie" },
  "mdblist.88333": { name: "[Top] Prime Shows", type: "series" },
  "mdblist.88434": { name: "[Top] Trakt's Trending Shows", type: "series" },
  "mdblist.88468": { name: "[Genre] Anime Movies", type: "movie" },
  "mdblist.88469": { name: "[Genre] Anime Shows", type: "series" },
  "mdblist.89366": { name: "[Top] Paramount+ Movies", type: "movie" },
  "mdblist.89647": { name: "[Service] HBO Max Movies", type: "movie" },
  "mdblist.89649": { name: "[Service] HBO Max Shows", type: "series" },
  "mdblist.91028": { name: "[Director] Stanley Kubrick", type: "movie" },
  "mdblist.91029": { name: "[Director] David Fincher", type: "movie" },
  "mdblist.91213": { name: "[Genre] Action Shows", type: "series" },
  "mdblist.91217": { name: "[Genre] Horror Shows", type: "series" },
  "mdblist.91221": { name: "[Genre] Fantasy/Sci-Fi Shows", type: "series" },
  "mdblist.91224": { name: "[Genre] Comedy Shows", type: "series" },
  "mdblist.91297": { name: "[Genre] Drama Shows", type: "series" },
  "mdblist.91300": { name: "[Year] Popular 1990s Movies", type: "movie" },
  "mdblist.91301": { name: "[Year] Popular 1980s Movies", type: "movie" },
  "mdblist.91302": { name: "[Year] Popular 2000s Movies", type: "movie" },
  "mdblist.91303": { name: "[Year] Popular 2010s Movies", type: "movie" },
  "mdblist.91304": { name: "[Year] Popular 2020s Movies", type: "movie" },
  "mdblist.91893": { name: "[Genre] Thriller Movies", type: "movie" },
  "mdblist.91894": { name: "[Genre] Thriller Shows", type: "series" },
  "mdblist.94304": { name: "[Collection] Lord of the Rings and Hobbit", type: "movie" },
  "mdblist.98039": { name: "[Collection] DC Movies", type: "movie" },
  "mdblist.98353": { name: "[Collection] Matrix", type: "movie" },
  "streaming.cru": { name: "[Service] Crunchyroll Shows", type: "anime" },
  "trakt.watchlist": { name: "[Discover] Watchlist", type: "all" }
};
